### ISSUE TITLE
Great Idea!

### ISSUE THREAD

**Issue by nickwynja** [themindfulbit/difficulties.github.io#1]
Erik, [Write Only](https://hess.fm/blog/write-only) is refreshing. I've been out of the blog game for a while but have found myself in a similar place as you seemed to be. I've been reducing my consumption overall for probably more than a year and it has felt great. I'm finally back in to the mood to be publishing online again and seeing other people like you refocus their online lives around their personal websites again is inspiring.

**Comment by themindfulbit** [comment]
@nickwynja Thanks Nick! And thanks for trying out my Github-issues-as-comments thing. Seemed subversive enough that it might actually work.

I think it's time for all of us with the means and experience to reinvest in our personal sites, with social media as mostly an amplifier. Glad to hear you've had a similar experience with your social media sabbatical. For me it's been critical.

Can't wait to read your new stuff! Have a great weekend, and thanks again for saying hi.
